/* Automatically generated by './build/bin/build-entry.js' */

import LgForm from '../packages/lg-form/index.js';
import LgFormTable from '../packages/lg-form-table/index.js';
import ButtonDemo from '../packages/button-demo/index.js';

const components = [
  LgForm,
  LgFormTable,
  ButtonDemo
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
  LgForm,
  LgFormTable,
  ButtonDemo
};
