/* Automatically generated by './build/bin/build-entry.js' */

import ButtonDemo from '../packages/button-demo/index.js';
import LgForm from '../packages/lg-form/index.js';
import LgFormTable from '../packages/lg-form-table/index.js';
import LgSampleTable from '../packages/lg-sample-table/index.js';
import LgSimpleSearchBar from '../packages/lg-simple-search-bar/index.js';

const components = [
  ButtonDemo,
  LgForm,
  LgFormTable,
  LgSampleTable,
  LgSimpleSearchBar
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  ButtonDemo,
  LgForm,
  LgFormTable,
  LgSampleTable,
  LgSimpleSearchBar
};
